apiVersion: v1
kind: Service
metadata:
  name: pick-bins-client-service
spec:
  selector:
    app: pick-bins-client-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
