apiVersion: apps/v1
kind: Deployment
metadata:
  name: pick-bins-server-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pick-bins-server-app
  template:
    metadata:
      labels:
        app: pick-bins-server-app
    spec:
      containers:
      - image: bipkar/pick-bins-server:latest
        name: server-image
        ports:
        - containerPort: 4000
        imagePullPolicy: Always
        # env:
        # - name: ME_CONFIG_MONGODB_SERVER
        #   valueFrom:
        #     configMapKeyRef:
        #       name: mongodb-configmap
        #       key: MONGODB_URL
